name: suggest a topic you'd like to read about
description: suggest a topic or prompt that you would read about. an important part of writing is writing for others. we will look to find an authors for your idea
body:
- type: textarea
  attributes:
    label: describe the topic you'd like to read about
    placeholder: "i'd like to read about using pandas to explore data."
  validations:
    required: true
- type: textarea
  attributes:
    label: please share some relevent links that you have looked prior to submitting this idea.
    placeholder: https://pandas.pydata.org/
- type: textarea
  attributes: 
    label: please name some modules you would like to see used together
    placeholder: pandas, requests, requests_cache
  
